name: "Build & Publish"
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  emanote:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: DeterminateSystems/nix-installer-action@main
        with:
          extra-conf: |
            trusted-public-keys = cache.garnix.io:CTFPyKSLcx5RMJKfLo5EEPUObbA78b0YQ2DTCJXqr9g= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=
            substituters = https://cache.garnix.io?priority=41 https://cache.nixos.org/
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - name: Build the website (Nix) 🔧
        run: |
          nix build -j 4
      - name: Deploy to gh-pages 🚀
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/master'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./result/
